title: Fotsing Kuetche
logo: "/img/mypic_10.png?raw=true"
description:
  Hi I’m Fotsing Kuetche, a dedicated educator and researcher specializing in machine learning and applied artificial intelligence. 
  With a solid background in science and technology, I am passionate about teaching, research, and innovation.
  <br><br>
  <a href="https://www.linkedin.com/in/fkuetche/">Let's Connect</a>
  <a href="mailto:fotsing.fk@gmail.com/">Let's Connect</a>
theme: jekyll-theme-minimal
